version:  '3.8'

# Réseau de l'hyperviseur
networks:
  vnet:
    ipam:
      driver: bridge
      config:
        - subnet: "172.17.0.0/16"

services:

## Serveur DNS via bind9 : internetsystemsconsortium/bind9 (v9.16) ##
  ns:
    image: backup-ns
    restart: unless-stopped
    container_name: ns
    ports:
      - 53:53/udp
      - 53:53/tcp
      - 953:953/tcp
    volumes:
      - /volume1/docker/projet-tutore/shared:/shared  
    networks:
      vnet:
        ipv4_address: 172.17.0.2

## Serveur PHP+PhpMyAdmin via Xampp : tomsik68/xampp (v8) ##
  www:
    image: backup-www
    restart: unless-stopped
    container_name: www
    ports:
      - 1443:1443
      - 180:180
      - 41061:22
    volumes:
      - /volume1/docker/rayane/projet-tut/www:/www
      - /volume1/docker/projet-tutore/shared:/shared
    networks:
      vnet:
        ipv4_address: 172.17.0.3

## Serveur VPN via OpenVPN : kylemanna/openvpn ##
  openvpn:
    image: backup-openvpn
    restart: unless-stopped
    container_name: openvpn
    ports:
      - 1194:1194/udp
    volumes:
      - /volume1/docker/rayane/openvpn/data:/etc/openvpn
      - /volume1/docker/projet-tutore/shared:/shared
    networks:
      vnet:
        ipv4_address: 172.17.0.4
    cap_add:
      - NET_ADMIN    

## Portainer = Gestion des containers docker : portainer/portainer-ce ##
  portainer:
    image: backup-portainer
    restart: unless-stopped
    container_name: portainer
    ports:
      - 9000:9000
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/projet-tutore/portainer:/data
      - /volume1/docker/projet-tutore/shared:/shared
    networks:
      vnet:
        ipv4_address: 172.17.0.5
    command: -H unix:///var/run/docker.sock    