version:  '3.8'

services:
## Serveur DNS via bind9 : internetsystemsconsortium/bind9 (v9.16) ##
  ns:
    image: backup-ns
    restart: unless-stopped
    container_name: ns
    ports:
      - 53:53/udp
      - 53:53/tcp
      - 953:953/tcp
    volumes:
      - /volume1/docker/rayane/shared:/shared  
    networks:
      projet:
        ipv4_address: 10.10.0.2

## Serveur PHP+PhpMyAdmin via Xampp : tomsik68/xampp (v8) ##
  www:
    image: backup-www
    restart: unless-stopped
    container_name: www
    ports:
      - 22:22/udp
      - 1443:1443
      - 180:180
    volumes:
      - /volume1/docker/rayane/www:/www
      - /volume1/docker/rayane/shared:/shared
    networks:
      projet:
        ipv4_address: 10.10.0.3

## Serveur VPN via OpenVPN : kylemanna/openvpn ##
  openvpn:
    image: backup-openvpn
    restart: unless-stopped
    container_name: openvpn
    ports:
      - 1194:1194/udp
    volumes:
      - /volume1/docker/rayane/openvpn/data:/etc/openvpn
      - /volume1/docker/rayane/shared:/shared
    networks:
      projet:
        ipv4_address: 10.10.0.4
    cap_add:
      - NET_ADMIN    

## Portainer = Gestion des containers docker : portainer/portainer-ce ##
  portainer:
    image: backup-portainer
    restart: unless-stopped
    container_name: portainer
    ports:
      - 9000:9000
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/rayane/portainer:/data
      - /volume1/docker/rayane/shared:/shared
    networks:
      projet:
        ipv4_address: 10.10.0.5
    command: -H unix:///var/run/docker.sock

## Portainer = Gestion des containers docker : portainer/portainer-ce ##
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: health-sprint.fr
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - /volume1/docker/rayane/docker-data/dms/mail-data/:/var/mail/
      - /volume1/docker/rayane/docker-data/dms/mail-state/:/var/mail-state/
      - /volume1/docker/rayane/docker-data/dms/mail-logs/:/var/log/mail/
      - /volume1/docker/rayane/docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ENABLE_SASLAUTHD=0
      - ONE_DIR=1
      - DMS_DEBUG=0
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always

# Réseau de l'hyperviseur
networks:
  projet:
    ipam:
      config:
        - subnet: "10.10.0.0/16"