version:  '3.8'
services:
## Serveur DNS via bind9 : internetsystemsconsortium/bind9 (v9.16) ##
  ns:
    image: internetsystemsconsortium/bind9:9.16
    restart: unless-stopped
    container_name: ns
    ports:
      - 53:53/udp
      - 53:53/tcp
      - 953:953/tcp
    volumes:
      - /volume1/docker/rayane/shared:/shared
    networks:
      projet:
        ipv4_address: 10.10.0.2

## Serveur PHP+PhpMyAdmin via Xampp : tomsik68/xampp (v8) ##
  www:
    image: backup-www
    restart: unless-stopped
    container_name: www
    ports:
      - 22:22/udp
      - 1443:1443
      - 180:180
    volumes:
      - /volume1/docker/rayane/www:/www
      - /volume1/docker/rayane/shared:/shared
    networks:
      projet:
        ipv4_address: 10.10.0.3

## Serveur VPN via OpenVPN : kylemanna/openvpn ##
  openvpn:
    image: backup-openvpn
    restart: unless-stopped
    container_name: openvpn
    ports:
      - 1194:1194/udp
    volumes:
      - /volume1/docker/rayane/openvpn/data:/etc/openvpn
      - /volume1/docker/rayane/shared:/shared
    networks:
      projet:
        ipv4_address: 10.10.0.4
    cap_add:
      - NET_ADMIN

## Portainer = Gestion des containers docker : portainer/portainer-ce ##
  portainer:
    image: backup-portainer
    restart: unless-stopped
    container_name: portainer
    ports:
      - 9000:9000
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/rayane/portainer:/data
      - /volume1/docker/rayane/shared:/shared
    networks:
      projet:
        ipv4_address: 10.10.0.5
    command: -H unix:///var/run/docker.sock

## OpenEMR = Electronic Medical Record : openemr/openemr:6.1.0 ##
  openemr:
    restart: always
    image: openemr/openemr:6.1.0
    ports:
    - 280:280
    - 2443:2443
    volumes:
    - logvolume01:/var/log
    - sitevolume:/var/www/localhost/htdocs/openemr/sites
    environment:
      MYSQL_HOST: www
      MYSQL_ROOT_PASS: Projet!94400
      OE_USER: admin
      OE_PASS: pass
    depends_on:
    - www
    networks:
      projet:
        ipv4_address: 10.10.0.6

## Orthanc : Dicom Viewer et PACS server ##
  orthanc:
    image: jodogne/orthanc-plugins:1.9.7
    command: /run/secrets  # Path to the configuration files (stored as secrets)
    container_name: orthanc
    ports:
      - 4242:4242
      - 8042:8042
    volumes:
      - /volume1/docker/rayane/orthanc/:/var/lib/orthanc/db/
      - /volume1/docker/rayane/secrets/:/run/secrets/
      - /volume1/docker/rayane/shared:/shared/
    environment:
      - ORTHANC_NAME=HealthSprint
    restart: unless-stopped
    networks:
      projet:
        ipv4_address: 10.10.0.7

# Reseau de l'hyperviseur
networks:
  projet:
    ipam:
      config:
        - subnet: "10.10.0.0/16"

volumes:
  logvolume01: {}
  sitevolume: {}
  databasevolume: {}